# Generated by Django 5.1 on 2024-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_verificationcode_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
